FROM node:24.15-alpine

WORKDIR /app

# Install openssl needed for Prisma engine
RUN apk add --no-cache openssl

# Install dependencies including devDependencies (needed for nest-cli & hot-reload)
COPY package*.json ./
RUN npm install

# Generate Prisma Client
COPY prisma ./prisma
RUN npx prisma generate

# Copy source code (during dev, volumes in docker-compose will override /app/src)
COPY . .

EXPOSE 3001

# Run NestJS in watch mode for instant Hot Reload
CMD ["npm", "run", "start:dev"]
